name: my-quarkus-components

services:

  quarkus-base-template:
    image: quarkus-base-template:latest
    container_name: quarkus-base-template
    depends_on:
      keycloak:
        condition: service_started
      mariadb:
        condition: service_started
    ports:
      - "8081:8080"


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOSTS: mariadb-service
      PMA_PORTS: 3306
      PMA_ARBITRARY: 1


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      KEYCLOAK_ADMIN: quarkus
      KEYCLOAK_ADMIN_PASSWORD: quarkus@123
      KC_DB: mariadb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: quarkus@123
      KC_DB_URL: jdbc:mariadb://mariadb-service:3306/keycloak
      KC_DB_POOL_INITIAL_SIZE: 5
      KC_DB_POOL_MIN_SIZE: 2
      KC_DB_POOL_MAX_SIZE: 10
      KC_LOG_LEVEL: DEBUG
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./realm:/opt/keycloak/data/import


  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: quarkus@123
      MARIADB_DATABASE: quarkus
      MARIADB_INITDB_SKIP_TZINFO: 1
      MARIADB_INITDB_WD: /docker-entrypoint-initdb.d
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d